myFirstApp/exchange/urls.py
from django.urls import path

from . import views


app_name = 'exchange'
urlpatterns = [ 
    #Quando roda o server ele vai na porta padrao localhost:8080, porem só funciona se se for localhost:8080/polls porque no arquivo 
    #urls.py da pasta de cima o primeiro path tem /polls no primeiro path
    path('', views.index, name='index'),
    path('login/',views.login, name='login'),
    path('telaLogin/',views.viewLogin, name="viewLogin"),
    path('details/<int:user_id>/',views.details, name='details'),
    path('wallet/<int:user_id>/', views.detail_wallet,name='wallet'),
    path('formUser/', views.formUser, name='formUser'),
    path('addUser/',views.addUser,name='addUser')
    #path('<str:user_name>/',views.detail_name, name='name')
]

myFirstApp/myFirstApp/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('exchange.urls')),
    path('admin/', admin.site.urls),
]

myFirstApp/exchange/models.py
from django.db import models

class User(models.Model):
    userName = models.CharField(max_length=45)
    passWord = models.CharField(max_length=30)
    userEmail = models.EmailField(max_length=30)

    def __str__(self):
        return f'User name = {self.userName}, User Email = {self.userEmail}'

    def getId(self):
        return self.id

class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    totalBalance = models.FloatField()     

    def __str__(self):
        return f"User = {self.user.userName}, Total Balance = {self.totalBalance}" 

class Coin(models.Model):
    coinName = models.CharField(max_length=10)
    value = models.FloatField()

    def __str__(self):
        return f"Coin Name = {self.coinName}, value = {self.value}"

class Active(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    coin = models.ForeignKey(Coin, on_delete=models.CASCADE)
    quantity = models.FloatField()

    def __str__(self):
        return f"Wallet = {self.wallet.id}, Coin = {self.coin}, Quantity = {self.quantity}"

myFirstApp/exchange/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

from .models import *

def index(request):
    return render(request, 'exchange/index.html')

def viewLogin(request):
    return render(request, 'exchange/login.html')

def login(request):

    print(request)
    userEmail_ = str(request.POST.get("userEmail"))
    userPassword_ = str(request.POST.get("userPassword"))

    print(userEmail_ + " " +userPassword_)

    user = ""
    userLista = User.objects.filter(userEmail = userEmail_, passWord = userPassword_)
    if len(userLista) > 0:
        user = userLista[0]
        return details(request, user.id)
    else:
        return HttpResponse("Nao encontrado")
    


def details(request, user_id):

    user = User.objects.get(id=user_id)

    wallet_user = Wallet.objects.get(user = user)

    actives = Active.objects.filter(wallet__id = wallet_user.id)

    context = {'user' : user, 'wallet' :  wallet_user, 'actives' : actives,}

    return render(request, 'exchange/user_details.html', context)


    '''active_string = "<br>".join([w.__str__() for w in actives])

    return HttpResponse(template_div(f'{user.__str__()}<br><br> {wallet_user.__str__()} <br><br> {active_string}'))
'''

def formUser(request):
    return render(request, 'exchange/add_user.html')

def addUser(request):

    userName_ = str(request.POST.get("userName"))
    userPassword_ = str(request.POST.get("passWord"))
    userEmail_ =  str(request.POST.get("userEmail"))

    new_user = User()

    new_user.userName = userName_
    new_user.passWord = userPassword_
    new_user.userEmail = userEmail_

    new_user.save()
    
    return HttpResponse(new_user)


def detail_wallet(request, user_id):

    user = User.objects.get(id=user_id)
    wallet_user = Wallet.objects.get(user = user)

    return HttpResponse(f'{wallet_user.__str__()}')

'''def detail_name(request, user_name):
    user = User.objects.get(userName = user_name)
    print(user)
    return HttpResponse(f"{user.__str__()}")'''

def template_div(text):
    return f"<div style='text-align:center'>{text}</div>"

myFirstApp/exchange/templates/exchange/add_user.html
<div style="text-align: center;">
        <form action="{% url 'exchange:addUser' %}" method="post">
                {% csrf_token %}
                <fieldset>
                        <legend>
                                <h1>Adicionando um Novo Usuario</h1>
                        </legend>
                        <label>Nome</label>
                        <input type="text" name="userName" id="userName">
                        <label>Senha</label>
                        <input type="password" name="passWord" id="passWord">
                        <label>Email</label>
                        <input type="email" name="userEmail" id="userEmail">
                </fieldset>
                <input type="submit" value="Adicionar">
        </form>
</div>

myFirstApp/exchange/templates/exchange/index.html
<div style="text-align: center;">
<h1>
    Bem vindo!!!
</h1>

<a href="{% url 'exchange:viewLogin' %}">Entrar</a>

</div>

myFirstApp/exchange/templates/exchange/login.html
{% load static %}
<!DOCTYPE html>
<html>
<title>Entrar</title>
<link rel="stylesheet" href="{% static 'login_view.css' %}">
<script src="{% static 'login_js.js' %}"></script>
<body>
    <div class="center" style="text-align: center;">
        <h2>Login</h2>
        <form method="post" action="{% url 'exchange:login' %}">
            {% csrf_token %}
            <div class="txtField">
                <input type="email" id="userEmail" name="userEmail" placeholder="" required>

                <label>Email</label>
            </div>
            <div class="txtField">
                <input type="password" id="userPassword" name="userPassword" placeholder="" required>

                <label>Password</label>
            </div>
            <div class="pass">Forgot Password?</div>
            <input type="submit" value="login">
            <div class="signup_link">
                Not a member? <a href="{% url 'exchange:formUser' %}">Singup</a>
            </div>
        </form>
    </div>
</body>


</html>

myFirstApp/exchange/templates/exchange/user_details.html
{% if user %}

    <div style="text-align: center;">
        {{ user }}<br>
        {{ wallet }}<br><br>
        {% for x in actives %}
            {{x}}<br>
        {% endfor %}
    </div>

{% endif %}